apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: gateway-error-rate
spec:
  args:
    - name: canary-hash
  metrics:
    - name: error-rate
      initialDelay: 60s
      interval: 20s
      count: 3
      successCondition: result[0] < 0.05
      failureLimit: 1
      provider:
        prometheus:
          address: http://prometheus.monitoring.svc.cluster.local:9090
          query: |
            (
              sum(rate(gateway_requests_total{rs_hash="{{args.canary-hash}}",status=~"5.."}[60s]))
              or on() vector(0)
            )
            /
            sum(rate(gateway_requests_total{rs_hash="{{args.canary-hash}}"}[60s]))
